{
 "title": "Company Store Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Store-1",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"100\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"100\"}[60s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Store-2",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[60s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Store-3",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"300\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"300\"}[60s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Store-4",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"400\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"400\"}[60s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Store-5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"500\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"500\"}[60s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Store Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"100\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"100\"}[60s])",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[60s])",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"300\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"300\"}[60s])",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"400\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"400\"}[60s])",
     "legendFormat": "{{ path }}"
    },
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"500\"}[60s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"500\"}[60s])",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}